### ISSUE TITLE
Can't import vue-xeditable

### ISSUE THREAD

**Issue by bomjastik** [Kar-Wai-Wong/vue-xeditable#6]
when I trying to import the package in my component:

`import Editable from 'vue-xeditable'`

I'm getting this during the `npm run dev`

![sketch 1](https://user-images.githubusercontent.com/1671780/33427564-5e9cc4ee-d5ce-11e7-950c-8e1166a0d48e.png)

` ERROR  Failed to compile with 1 errors`                                                                                                                                              
`This dependency was not found:`
`* vue-xeditable in ./node_modules/babel-loader/lib...`
`To install it, you can run: npm install --save vue-xeditable`

My node_modules and package.json:
![2](https://user-images.githubusercontent.com/1671780/33427682-cfc27222-d5ce-11e7-9d30-4b0ef24478ba.png)

Windows 10
Laravel Homestead + Vagrant
npm -v: 5.6.0

**Comment by ibanjo** [comment]
I've had the same problem. In my main.js file I used:

`import Editable from 'vue-xeditable/src/Editable';
window.Vue.use(Editable);`

Now, however, I get a weird "jQuery not found"-like error

`app.js:41480 Uncaught Error: Bootstrap's JavaScript requires jQuery`

That I really can't explain, because I'm sure that jQuery was imported even before Editable.vue. I think this might be a Webpack-related issue.

**Comment by ibanjo** [comment]
OK, I found a workaround. In your main.js just use

```javascript
window.Editable = require('vue-xeditable/src/Editable.vue');
```
and then follow the documentation as it already is.
